### ISSUE TITLE
link to the invite on slack is broken

### ISSUE THREAD

**Issue by jchassoul** [lua-users-foundation/foundation#6]
This invite link is no longer active. )=

**Comment by Etiene** [comment]
Fixed! here is the new link https://join.slack.com/t/lua-users-foundation/shared_invite/enQtMzM2ODEwMDI4MjQ0LTJhMWY5ODU1ZTdkMmZkMTgxOWIwMDNkOTdhZWFmM2NiY2FiOWRhZDYxOTMxZGFiYWViOGIwZDgwZDZmYWZhYjM

thanks for reporting
